# Generated by Django 3.0.3 on 2020-05-14 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la cita')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('estimated_price', models.FloatField(blank=True, null=True, verbose_name='Precio estimado')),
                ('estimated_discount', models.FloatField(blank=True, null=True, verbose_name='Descuento estimado (valor)')),
                ('estimated_discount_rate', models.FloatField(blank=True, null=True, verbose_name='Descuento estimado (tasa)')),
                ('estimated_duration', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Duración estimada en minutos')),
                ('final_price', models.FloatField(blank=True, null=True, verbose_name='Precio estimado')),
                ('final_discount', models.FloatField(blank=True, null=True, verbose_name='Descuento estimado (valor)')),
                ('final_discount_rate', models.FloatField(blank=True, null=True, verbose_name='Descuento estimado (tasa)')),
                ('final_duration', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Duración estimada en minutos')),
                ('rating', models.CharField(blank=True, max_length=20, null=True, verbose_name='Calificación')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('status', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada')], default='PENDIENTE', max_length=100, null=True, verbose_name='Estado')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbero', to=settings.AUTH_USER_MODEL, verbose_name='Peluquero/Barbero')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('product', models.ManyToManyField(blank=True, to='products.Product', verbose_name='Servicio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
