# Generated by Django 3.0.3 on 2020-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
