# Generated by Django 3.0.3 on 2020-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200514_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='final_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento final (valor)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_discount_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento final (tasa)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_duration',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Duración final en minutos'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio final'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En proceso'), ('RECHAZADA', 'Rechazada'), ('REALIZADA', 'Realizada')], default='PENDIENTE', max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
